apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-indexed
  namespace: encoding
data:
  default.conf: |
    server {
        listen 80;
        
        location /encodedVideos/ {
            alias /usr/share/nginx/html/encodedVideos/;
            index  index.html;
            autoindex on;
        }

        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

  index.html: |
    <html>
     <head>
         <meta charset="UTF-8" />
         <title>Videos Transcodificados</title>
     </head>
     <body>
         <h1>Videos Transcodificados</h1>
     </body>
     </html>
