apiVersion: v1
kind: Service
metadata:
  name: svc-upload-nginx
  namespace: pf
spec:
  type: ClusterIP
  selector:
    app: upload-nginx
  ports:
  - name: nginx
    port: 80
    targetPort: 80
  - name: upload 
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-transcoding
  namespace: pf
spec:
  type: ClusterIP
  selector:
    app: transcoding
  ports:
  - port: 8080
    targetPort: 8080
