apiVersion: v1
kind: Secret
metadata:
  name: mdb-secrets
  namespace: metrics
type: kubernetes.io/basic-auth # Recomendado por la documentacion de kubernete pero Opaque tambien seria adecuado
data:
  username: YWRtaW4K
  password: cGFzc3dvcmQK